<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="32" total="41" passed="6" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-18T17:43:43 IST" name="Suite_to_automate_SIM" finished-at="2024-12-18T17:46:16 IST" duration-ms="152979">
    <groups>
    </groups>
    <test started-at="2024-12-18T17:43:43 IST" name="Test" finished-at="2024-12-18T17:46:16 IST" duration-ms="152979">
      <class name="Sim_automation.EstimateCreation">
        <test-method signature="Estimateform()[pri:6, instance:Sim_automation.EstimateCreation@4218d6a3]" started-at="2024-12-18T17:45:33 IST" name="Estimateform" description="Add an Estimate in the SIM-Web App" finished-at="2024-12-18T17:45:50 IST" duration-ms="17060" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Estimateform -->
      </class> <!-- Sim_automation.EstimateCreation -->
      <class name="Sim_automation.PaymentReceivedCreation">
        <test-method signature="paymentRecivedForm()[pri:7, instance:Sim_automation.PaymentReceivedCreation@34123d65]" started-at="2024-12-18T17:45:50 IST" name="paymentRecivedForm" description="Add a Payment (Received) in the SIM-Web App" finished-at="2024-12-18T17:46:07 IST" duration-ms="16789" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Form open to fill up Details for the receipt of the corresponding Payment expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Form open to fill up Details for the receipt of the corresponding Payment expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at Sim_automation.PaymentReceivedCreation.paymentRecivedForm(PaymentReceivedCreation.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentRecivedForm -->
      </class> <!-- Sim_automation.PaymentReceivedCreation -->
      <class name="Sim_automation.SaleOrderCreation">
        <test-method signature="SaleOrderform()[pri:5, instance:Sim_automation.SaleOrderCreation@4802796d]" started-at="2024-12-18T17:45:15 IST" name="SaleOrderform" description="Add an SaleOrder in the SIM-Web App" finished-at="2024-12-18T17:45:33 IST" duration-ms="17249" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SaleOrderform -->
      </class> <!-- Sim_automation.SaleOrderCreation -->
      <class name="Sim_automation.Login">
        <test-method is-config="true" signature="reportGenerate()[pri:0, instance:Sim_automation.Login@35d019a3]" started-at="2024-12-18T17:43:42 IST" name="reportGenerate" finished-at="2024-12-18T17:43:43 IST" duration-ms="206" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportGenerate -->
        <test-method is-config="true" signature="browserOpen()[pri:0, instance:Sim_automation.Login@35d019a3]" started-at="2024-12-18T17:43:43 IST" name="browserOpen" finished-at="2024-12-18T17:43:58 IST" duration-ms="15879" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserOpen -->
        <test-method signature="logindata()[pri:1, instance:Sim_automation.Login@35d019a3]" started-at="2024-12-18T17:43:58 IST" name="logindata" description="Login in the SIM-Web App" finished-at="2024-12-18T17:44:13 IST" duration-ms="14348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindata -->
        <test-method is-config="true" signature="logout()[pri:0, instance:Sim_automation.Login@35d019a3]" started-at="2024-12-18T17:46:15 IST" name="logout" finished-at="2024-12-18T17:46:16 IST" duration-ms="139" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:Sim_automation.Login@35d019a3]" started-at="2024-12-18T17:46:16 IST" name="endReport" finished-at="2024-12-18T17:46:16 IST" duration-ms="281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- Sim_automation.Login -->
      <class name="Sim_automation.PaymentPaidCreation">
        <test-method signature="paymentPecivedForm()[pri:8, instance:Sim_automation.PaymentPaidCreation@59474f18]" started-at="2024-12-18T17:46:07 IST" name="paymentPecivedForm" description="Add a Payment (Paid) in the SIM-Web App" finished-at="2024-12-18T17:46:08 IST" duration-ms="1117" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Payment List Form Open expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Payment List Form Open expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at Sim_automation.PaymentPaidCreation.paymentPecivedForm(PaymentPaidCreation.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentPecivedForm -->
      </class> <!-- Sim_automation.PaymentPaidCreation -->
      <class name="Sim_automation.InvoiceCreation">
        <test-method signature="invoiceform()[pri:3, instance:Sim_automation.InvoiceCreation@71d44a3]" started-at="2024-12-18T17:44:34 IST" name="invoiceform" description="Add an Invoice in the SIM-Web App" finished-at="2024-12-18T17:44:58 IST" duration-ms="23381" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invoiceform -->
      </class> <!-- Sim_automation.InvoiceCreation -->
      <class name="Sim_automation.PurchaseCreation">
        <test-method signature="Purchaseform()[pri:2, instance:Sim_automation.PurchaseCreation@73a1e9a9]" started-at="2024-12-18T17:44:13 IST" name="Purchaseform" description="Add a Purchase in the SIM-Web App" finished-at="2024-12-18T17:44:34 IST" duration-ms="21643" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Purchaseform -->
      </class> <!-- Sim_automation.PurchaseCreation -->
      <class name="Sim_automation.PurchaseOrderCreation">
        <test-method signature="PurchaseOrderform()[pri:4, instance:Sim_automation.PurchaseOrderCreation@7b98f307]" started-at="2024-12-18T17:44:58 IST" name="PurchaseOrderform" description="Add an PurchaseOrder in the SIM-Web App" finished-at="2024-12-18T17:45:15 IST" duration-ms="17623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PurchaseOrderform -->
      </class> <!-- Sim_automation.PurchaseOrderCreation -->
      <class name="Sim_automation.LogOut">
        <test-method signature="logOutdata()[pri:9, instance:Sim_automation.LogOut@65fb9ffc]" started-at="2024-12-18T17:46:08 IST" name="logOutdata" description="Log-Out From the SIM-Web App" finished-at="2024-12-18T17:46:15 IST" duration-ms="7333" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[USer Log-Out From the SIM-Web App successfully expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: USer Log-Out From the SIM-Web App successfully expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at Sim_automation.LogOut.logOutdata(LogOut.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOutdata -->
      </class> <!-- Sim_automation.LogOut -->
    </test> <!-- Test -->
  </suite> <!-- Suite_to_automate_SIM -->
</testng-results>
